language: php

dist: bionic
php:
  - '8.1.0'
  - '8.0'
  - '7.4'
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - XDEBUG_MODE=coverage ./vendor/phpunit/phpunit/phpunit --coverage-html docs/tests/
  - XDEBUG_MODE=coverage ./vendor/phpunit/phpunit/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)


